#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 83
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 44
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 17

enum {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  anon_sym_EQ = 3,
  sym_break_statement = 4,
  sym_continue_statement = 5,
  anon_sym_return = 6,
  anon_sym_if = 7,
  anon_sym_elif = 8,
  anon_sym_else = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  sym_comment = 12,
  anon_sym_Boolean = 13,
  anon_sym_Date = 14,
  anon_sym_Float = 15,
  anon_sym_Integer = 16,
  anon_sym_String = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  anon_sym_DOT = 20,
  anon_sym_LPAREN = 21,
  anon_sym_COMMA = 22,
  anon_sym_RPAREN = 23,
  anon_sym_not = 24,
  anon_sym_DASH = 25,
  anon_sym_PLUS = 26,
  anon_sym_STAR = 27,
  anon_sym_SLASH = 28,
  anon_sym_PERCENT = 29,
  anon_sym_and = 30,
  anon_sym_or = 31,
  anon_sym_EQ_EQ = 32,
  anon_sym_LT_GT = 33,
  anon_sym_GT = 34,
  anon_sym_LT = 35,
  anon_sym_LT_EQ = 36,
  anon_sym_GT_EQ = 37,
  sym_number_literal = 38,
  sym_string_literal = 39,
  anon_sym_print = 40,
  sym_true = 41,
  sym_false = 42,
  sym_null = 43,
  sym_source_file = 44,
  sym__statement = 45,
  sym__statement_list = 46,
  sym__simple_statement = 47,
  sym_assignment_statement = 48,
  sym_return_statement = 49,
  sym_if_statement = 50,
  sym_block = 51,
  sym__expression = 52,
  sym__type = 53,
  sym_subscript_expression = 54,
  sym_array_declaration = 55,
  sym_call_expression = 56,
  sym_argument_list = 57,
  sym_unary_expression = 58,
  sym_binary_expression = 59,
  sym_parenthesized_expression = 60,
  sym_print = 61,
  aux_sym_source_file_repeat1 = 62,
  aux_sym__statement_list_repeat1 = 63,
  aux_sym_if_statement_repeat1 = 64,
  aux_sym_subscript_expression_repeat1 = 65,
  aux_sym_array_declaration_repeat1 = 66,
  aux_sym_call_expression_repeat1 = 67,
  aux_sym_argument_list_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [sym_break_statement] = "break_statement",
  [sym_continue_statement] = "continue_statement",
  [anon_sym_return] = "return",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_comment] = "comment",
  [anon_sym_Boolean] = "Boolean",
  [anon_sym_Date] = "Date",
  [anon_sym_Float] = "Float",
  [anon_sym_Integer] = "Integer",
  [anon_sym_String] = "String",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_not] = "not",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [sym_number_literal] = "number_literal",
  [sym_string_literal] = "string_literal",
  [anon_sym_print] = "print",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym__statement_list] = "_statement_list",
  [sym__simple_statement] = "_simple_statement",
  [sym_assignment_statement] = "assignment_statement",
  [sym_return_statement] = "return_statement",
  [sym_if_statement] = "if_statement",
  [sym_block] = "block",
  [sym__expression] = "_expression",
  [sym__type] = "_type",
  [sym_subscript_expression] = "subscript_expression",
  [sym_array_declaration] = "array_declaration",
  [sym_call_expression] = "call_expression",
  [sym_argument_list] = "argument_list",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_print] = "print",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__statement_list_repeat1] = "_statement_list_repeat1",
  [aux_sym_if_statement_repeat1] = "if_statement_repeat1",
  [aux_sym_subscript_expression_repeat1] = "subscript_expression_repeat1",
  [aux_sym_array_declaration_repeat1] = "array_declaration_repeat1",
  [aux_sym_call_expression_repeat1] = "call_expression_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_break_statement] = sym_break_statement,
  [sym_continue_statement] = sym_continue_statement,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_comment] = sym_comment,
  [anon_sym_Boolean] = anon_sym_Boolean,
  [anon_sym_Date] = anon_sym_Date,
  [anon_sym_Float] = anon_sym_Float,
  [anon_sym_Integer] = anon_sym_Integer,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [sym_number_literal] = sym_number_literal,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_print] = anon_sym_print,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym__statement_list] = sym__statement_list,
  [sym__simple_statement] = sym__simple_statement,
  [sym_assignment_statement] = sym_assignment_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_block] = sym_block,
  [sym__expression] = sym__expression,
  [sym__type] = sym__type,
  [sym_subscript_expression] = sym_subscript_expression,
  [sym_array_declaration] = sym_array_declaration,
  [sym_call_expression] = sym_call_expression,
  [sym_argument_list] = sym_argument_list,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_print] = sym_print,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__statement_list_repeat1] = aux_sym__statement_list_repeat1,
  [aux_sym_if_statement_repeat1] = aux_sym_if_statement_repeat1,
  [aux_sym_subscript_expression_repeat1] = aux_sym_subscript_expression_repeat1,
  [aux_sym_array_declaration_repeat1] = aux_sym_array_declaration_repeat1,
  [aux_sym_call_expression_repeat1] = aux_sym_call_expression_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_break_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_continue_statement] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Integer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__statement_list] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_subscript_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_array_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_print] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subscript_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alternative = 1,
  field_argument = 2,
  field_arguments = 3,
  field_condition = 4,
  field_consequence = 5,
  field_function = 6,
  field_index = 7,
  field_left = 8,
  field_operator = 9,
  field_right = 10,
  field_size = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_argument] = "argument",
  [field_arguments] = "arguments",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_function] = "function",
  [field_index] = "index",
  [field_left] = "left",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_size] = "size",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 3},
  [7] = {.index = 12, .length = 2},
  [8] = {.index = 14, .length = 4},
  [9] = {.index = 18, .length = 2},
  [10] = {.index = 20, .length = 1},
  [11] = {.index = 21, .length = 3},
  [12] = {.index = 24, .length = 4},
  [13] = {.index = 28, .length = 3},
  [14] = {.index = 31, .length = 2},
  [15] = {.index = 33, .length = 2},
  [16] = {.index = 35, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument, 1},
    {field_operator, 0},
  [2] =
    {field_arguments, 1},
    {field_function, 0},
  [4] =
    {field_size, 1, .inherited = true},
  [5] =
    {field_condition, 1},
    {field_consequence, 2},
  [7] =
    {field_arguments, 2},
    {field_function, 0},
  [9] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [12] =
    {field_size, 0, .inherited = true},
    {field_size, 1, .inherited = true},
  [14] =
    {field_alternative, 3, .inherited = true},
    {field_condition, 1},
    {field_condition, 3, .inherited = true},
    {field_consequence, 2},
  [18] =
    {field_argument, 0},
    {field_index, 2},
  [20] =
    {field_size, 1},
  [21] =
    {field_alternative, 4},
    {field_condition, 1},
    {field_consequence, 2},
  [24] =
    {field_alternative, 0, .inherited = true},
    {field_alternative, 1, .inherited = true},
    {field_condition, 0, .inherited = true},
    {field_condition, 1, .inherited = true},
  [28] =
    {field_argument, 0},
    {field_index, 2},
    {field_index, 4, .inherited = true},
  [31] =
    {field_alternative, 2},
    {field_condition, 1},
  [33] =
    {field_index, 0, .inherited = true},
    {field_index, 1, .inherited = true},
  [35] =
    {field_index, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '%') ADVANCE(33);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(26);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == ',') ADVANCE(27);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(25);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ';') ADVANCE(16);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '=') ADVANCE(17);
      if (lookahead == '>') ADVANCE(36);
      if (lookahead == '[') ADVANCE(22);
      if (lookahead == '\\') SKIP(11)
      if (lookahead == ']') ADVANCE(23);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(4)
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(4)
      if (lookahead == '\r') SKIP(1)
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(33);
      if (lookahead == '(') ADVANCE(26);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == ',') ADVANCE(27);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ';') ADVANCE(16);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '=') ADVANCE(17);
      if (lookahead == '>') ADVANCE(36);
      if (lookahead == '[') ADVANCE(22);
      if (lookahead == '\\') SKIP(2)
      if (lookahead == ']') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 10:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(0)
      END_STATE();
    case 11:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(0)
      if (lookahead == '\r') SKIP(10)
      END_STATE();
    case 12:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(14)
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(14)
      if (lookahead == '\r') SKIP(12)
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(26);
      if (lookahead == ')') ADVANCE(28);
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ';') ADVANCE(16);
      if (lookahead == '\\') SKIP(13)
      if (lookahead == ']') ADVANCE(23);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(21);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == '>') ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'B') ADVANCE(1);
      if (lookahead == 'D') ADVANCE(2);
      if (lookahead == 'F') ADVANCE(3);
      if (lookahead == 'I') ADVANCE(4);
      if (lookahead == 'S') ADVANCE(5);
      if (lookahead == '\\') SKIP(6)
      if (lookahead == 'a') ADVANCE(7);
      if (lookahead == 'b') ADVANCE(8);
      if (lookahead == 'c') ADVANCE(9);
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == 'f') ADVANCE(11);
      if (lookahead == 'i') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(13);
      if (lookahead == 'o') ADVANCE(14);
      if (lookahead == 'p') ADVANCE(15);
      if (lookahead == 'r') ADVANCE(16);
      if (lookahead == 't') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(0)
      if (lookahead == '\r') SKIP(23)
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(30);
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 23:
      if (lookahead == '\n') SKIP(0)
      END_STATE();
    case 24:
      if (lookahead == 'd') ADVANCE(41);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 33:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 38:
      if (lookahead == 'a') ADVANCE(54);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(56);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 42:
      if (lookahead == 'a') ADVANCE(57);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 44:
      if (lookahead == 'f') ADVANCE(59);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(61);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(63);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(64);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_Date);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 55:
      if (lookahead == 'g') ADVANCE(68);
      END_STATE();
    case 56:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 57:
      if (lookahead == 'k') ADVANCE(70);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(71);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 64:
      if (lookahead == 'r') ADVANCE(74);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 66:
      if (lookahead == 'a') ADVANCE(75);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_Float);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 69:
      if (lookahead == 'g') ADVANCE(77);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_break_statement);
      END_STATE();
    case 71:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    case 74:
      if (lookahead == 'n') ADVANCE(79);
      END_STATE();
    case 75:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(81);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 78:
      if (lookahead == 'u') ADVANCE(82);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_Boolean);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_Integer);
      END_STATE();
    case 82:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_continue_statement);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 14},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 14},
  [28] = {.lex_state = 14},
  [29] = {.lex_state = 14},
  [30] = {.lex_state = 14},
  [31] = {.lex_state = 14},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_break_statement] = ACTIONS(1),
    [sym_continue_statement] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Boolean] = ACTIONS(1),
    [anon_sym_Date] = ACTIONS(1),
    [anon_sym_Float] = ACTIONS(1),
    [anon_sym_Integer] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(81),
    [sym__statement] = STATE(3),
    [sym__simple_statement] = STATE(3),
    [sym_assignment_statement] = STATE(79),
    [sym_return_statement] = STATE(3),
    [sym_if_statement] = STATE(3),
    [sym_block] = STATE(3),
    [sym__expression] = STATE(57),
    [sym__type] = STATE(38),
    [sym_subscript_expression] = STATE(57),
    [sym_array_declaration] = STATE(57),
    [sym_call_expression] = STATE(57),
    [sym_unary_expression] = STATE(57),
    [sym_binary_expression] = STATE(57),
    [sym_parenthesized_expression] = STATE(57),
    [sym_print] = STATE(57),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_break_statement] = ACTIONS(9),
    [sym_continue_statement] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Boolean] = ACTIONS(17),
    [anon_sym_Date] = ACTIONS(17),
    [anon_sym_Float] = ACTIONS(17),
    [anon_sym_Integer] = ACTIONS(17),
    [anon_sym_String] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_not] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [sym_number_literal] = ACTIONS(25),
    [sym_string_literal] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(27),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
  },
  [2] = {
    [sym__statement] = STATE(2),
    [sym__simple_statement] = STATE(2),
    [sym_assignment_statement] = STATE(79),
    [sym_return_statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_block] = STATE(2),
    [sym__expression] = STATE(57),
    [sym__type] = STATE(38),
    [sym_subscript_expression] = STATE(57),
    [sym_array_declaration] = STATE(57),
    [sym_call_expression] = STATE(57),
    [sym_unary_expression] = STATE(57),
    [sym_binary_expression] = STATE(57),
    [sym_parenthesized_expression] = STATE(57),
    [sym_print] = STATE(57),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_identifier] = ACTIONS(33),
    [sym_break_statement] = ACTIONS(36),
    [sym_continue_statement] = ACTIONS(36),
    [anon_sym_return] = ACTIONS(39),
    [anon_sym_if] = ACTIONS(42),
    [anon_sym_LBRACE] = ACTIONS(45),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Boolean] = ACTIONS(48),
    [anon_sym_Date] = ACTIONS(48),
    [anon_sym_Float] = ACTIONS(48),
    [anon_sym_Integer] = ACTIONS(48),
    [anon_sym_String] = ACTIONS(48),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_not] = ACTIONS(54),
    [anon_sym_DASH] = ACTIONS(57),
    [anon_sym_PLUS] = ACTIONS(57),
    [sym_number_literal] = ACTIONS(60),
    [sym_string_literal] = ACTIONS(60),
    [anon_sym_print] = ACTIONS(63),
    [sym_true] = ACTIONS(66),
    [sym_false] = ACTIONS(66),
    [sym_null] = ACTIONS(66),
  },
  [3] = {
    [sym__statement] = STATE(2),
    [sym__simple_statement] = STATE(2),
    [sym_assignment_statement] = STATE(79),
    [sym_return_statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_block] = STATE(2),
    [sym__expression] = STATE(57),
    [sym__type] = STATE(38),
    [sym_subscript_expression] = STATE(57),
    [sym_array_declaration] = STATE(57),
    [sym_call_expression] = STATE(57),
    [sym_unary_expression] = STATE(57),
    [sym_binary_expression] = STATE(57),
    [sym_parenthesized_expression] = STATE(57),
    [sym_print] = STATE(57),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(7),
    [sym_break_statement] = ACTIONS(9),
    [sym_continue_statement] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Boolean] = ACTIONS(17),
    [anon_sym_Date] = ACTIONS(17),
    [anon_sym_Float] = ACTIONS(17),
    [anon_sym_Integer] = ACTIONS(17),
    [anon_sym_String] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_not] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [sym_number_literal] = ACTIONS(25),
    [sym_string_literal] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(27),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
  },
  [4] = {
    [sym__statement] = STATE(70),
    [sym__statement_list] = STATE(82),
    [sym__simple_statement] = STATE(70),
    [sym_assignment_statement] = STATE(79),
    [sym_return_statement] = STATE(70),
    [sym_if_statement] = STATE(70),
    [sym_block] = STATE(70),
    [sym__expression] = STATE(57),
    [sym__type] = STATE(38),
    [sym_subscript_expression] = STATE(57),
    [sym_array_declaration] = STATE(57),
    [sym_call_expression] = STATE(57),
    [sym_unary_expression] = STATE(57),
    [sym_binary_expression] = STATE(57),
    [sym_parenthesized_expression] = STATE(57),
    [sym_print] = STATE(57),
    [sym_identifier] = ACTIONS(7),
    [sym_break_statement] = ACTIONS(9),
    [sym_continue_statement] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(71),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Boolean] = ACTIONS(17),
    [anon_sym_Date] = ACTIONS(17),
    [anon_sym_Float] = ACTIONS(17),
    [anon_sym_Integer] = ACTIONS(17),
    [anon_sym_String] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_not] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [sym_number_literal] = ACTIONS(25),
    [sym_string_literal] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(27),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
  },
  [5] = {
    [sym__statement] = STATE(74),
    [sym__simple_statement] = STATE(74),
    [sym_assignment_statement] = STATE(79),
    [sym_return_statement] = STATE(74),
    [sym_if_statement] = STATE(74),
    [sym_block] = STATE(74),
    [sym__expression] = STATE(57),
    [sym__type] = STATE(38),
    [sym_subscript_expression] = STATE(57),
    [sym_array_declaration] = STATE(57),
    [sym_call_expression] = STATE(57),
    [sym_unary_expression] = STATE(57),
    [sym_binary_expression] = STATE(57),
    [sym_parenthesized_expression] = STATE(57),
    [sym_print] = STATE(57),
    [sym_identifier] = ACTIONS(7),
    [sym_break_statement] = ACTIONS(9),
    [sym_continue_statement] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Boolean] = ACTIONS(17),
    [anon_sym_Date] = ACTIONS(17),
    [anon_sym_Float] = ACTIONS(17),
    [anon_sym_Integer] = ACTIONS(17),
    [anon_sym_String] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_not] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [sym_number_literal] = ACTIONS(25),
    [sym_string_literal] = ACTIONS(25),
    [anon_sym_print] = ACTIONS(27),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_elif,
    ACTIONS(79), 1,
      anon_sym_else,
    STATE(9), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(73), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(75), 15,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_return,
      anon_sym_if,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
      anon_sym_not,
      sym_identifier,
      anon_sym_print,
      sym_true,
      sym_false,
      sym_null,
  [41] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_elif,
    STATE(7), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(81), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(83), 15,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_return,
      anon_sym_if,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
      anon_sym_not,
      sym_identifier,
      anon_sym_print,
      sym_true,
      sym_false,
      sym_null,
  [79] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(90), 17,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_return,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
      anon_sym_not,
      sym_identifier,
      anon_sym_print,
      sym_true,
      sym_false,
      sym_null,
  [113] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_elif,
    STATE(7), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(92), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(94), 15,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_return,
      anon_sym_if,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
      anon_sym_not,
      sym_identifier,
      anon_sym_print,
      sym_true,
      sym_false,
      sym_null,
  [151] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    ACTIONS(96), 1,
      anon_sym_SEMI,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(98), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(100), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(60), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [203] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    ACTIONS(102), 1,
      anon_sym_RBRACK,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(106), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(59), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [255] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(110), 17,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_return,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
      anon_sym_not,
      sym_identifier,
      anon_sym_print,
      sym_true,
      sym_false,
      sym_null,
  [289] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(114), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(116), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(56), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [341] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(118), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(120), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(55), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [390] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(122), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(124), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(49), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [439] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(128), 16,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_return,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
      anon_sym_not,
      sym_identifier,
      anon_sym_print,
      sym_true,
      sym_false,
      sym_null,
  [472] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(130), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(132), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(58), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [521] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(134), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(136), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(63), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [570] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(138), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(140), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(51), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [619] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(142), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(144), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(50), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [668] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(146), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(148), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(64), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [717] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(150), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(152), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(61), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [766] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(154), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(156), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(43), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [815] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(158), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(160), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(62), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [864] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(162), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(164), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(48), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [913] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(166), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(168), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(47), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [962] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_not,
    ACTIONS(27), 1,
      anon_sym_print,
    STATE(38), 1,
      sym__type,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(170), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(172), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(17), 5,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
    STATE(46), 8,
      sym__expression,
      sym_subscript_expression,
      sym_array_declaration,
      sym_call_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
      sym_print,
  [1011] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(176), 15,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_return,
      anon_sym_if,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
      anon_sym_not,
      sym_identifier,
      anon_sym_print,
      sym_true,
      sym_false,
      sym_null,
  [1043] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(180), 15,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_return,
      anon_sym_if,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
      anon_sym_not,
      sym_identifier,
      anon_sym_print,
      sym_true,
      sym_false,
      sym_null,
  [1075] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(184), 15,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_return,
      anon_sym_if,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
      anon_sym_not,
      sym_identifier,
      anon_sym_print,
      sym_true,
      sym_false,
      sym_null,
  [1107] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(188), 15,
      sym_break_statement,
      sym_continue_statement,
      anon_sym_return,
      anon_sym_if,
      anon_sym_Boolean,
      anon_sym_Date,
      anon_sym_Float,
      anon_sym_Integer,
      anon_sym_String,
      anon_sym_not,
      sym_identifier,
      anon_sym_print,
      sym_true,
      sym_false,
      sym_null,
  [1139] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_LBRACK,
    ACTIONS(196), 1,
      anon_sym_DOT,
    ACTIONS(198), 1,
      anon_sym_LPAREN,
    STATE(52), 1,
      sym_argument_list,
    STATE(65), 1,
      aux_sym_call_expression_repeat1,
    ACTIONS(192), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(190), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1180] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_LBRACK,
    STATE(33), 1,
      aux_sym_subscript_expression_repeat1,
    ACTIONS(202), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(200), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1212] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    STATE(35), 1,
      aux_sym_subscript_expression_repeat1,
    ACTIONS(209), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(207), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1244] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    STATE(33), 1,
      aux_sym_subscript_expression_repeat1,
    ACTIONS(215), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(213), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1276] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_LBRACK,
    STATE(37), 1,
      aux_sym_array_declaration_repeat1,
    ACTIONS(219), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(217), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1308] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_LBRACK,
    STATE(37), 1,
      aux_sym_array_declaration_repeat1,
    ACTIONS(225), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(223), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1340] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_LBRACK,
    STATE(36), 1,
      aux_sym_array_declaration_repeat1,
    ACTIONS(232), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(230), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1372] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(234), 15,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1399] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(238), 15,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1426] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(242), 15,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(246), 15,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1480] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_EQ,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(250), 5,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_or,
  [1520] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(268), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1546] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(272), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1572] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(252), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(250), 12,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1602] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(250), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1628] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_EQ,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(250), 6,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
  [1666] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(278), 1,
      anon_sym_EQ,
    ACTIONS(280), 1,
      anon_sym_or,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(276), 4,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1708] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_EQ,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(250), 8,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
  [1744] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(252), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(250), 10,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1776] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(282), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1802] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(286), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1828] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(290), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1854] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 4,
      anon_sym_EQ,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(294), 14,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1880] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(280), 1,
      anon_sym_or,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1922] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(280), 1,
      anon_sym_or,
    ACTIONS(302), 1,
      anon_sym_SEMI,
    ACTIONS(304), 1,
      anon_sym_EQ,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1961] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(280), 1,
      anon_sym_or,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(306), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1998] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(280), 1,
      anon_sym_or,
    ACTIONS(308), 1,
      anon_sym_RBRACK,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2034] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(280), 1,
      anon_sym_or,
    ACTIONS(310), 1,
      anon_sym_SEMI,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2070] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(280), 1,
      anon_sym_or,
    ACTIONS(312), 1,
      anon_sym_SEMI,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2106] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(280), 1,
      anon_sym_or,
    ACTIONS(314), 1,
      anon_sym_RBRACK,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2142] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(280), 1,
      anon_sym_or,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2178] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SLASH,
    ACTIONS(260), 1,
      anon_sym_and,
    ACTIONS(280), 1,
      anon_sym_or,
    ACTIONS(318), 1,
      anon_sym_RBRACK,
    ACTIONS(254), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(256), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(262), 2,
      anon_sym_EQ_EQ,
      anon_sym_LT_GT,
    ACTIONS(264), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(266), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2214] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_DOT,
    ACTIONS(198), 1,
      anon_sym_LPAREN,
    STATE(45), 1,
      sym_argument_list,
    STATE(69), 1,
      aux_sym_call_expression_repeat1,
  [2230] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_SEMI,
    ACTIONS(323), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym__statement_list_repeat1,
  [2243] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_SEMI,
    ACTIONS(327), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym__statement_list_repeat1,
  [2256] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    ACTIONS(329), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_argument_list_repeat1,
  [2269] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_DOT,
    ACTIONS(334), 1,
      anon_sym_LPAREN,
    STATE(69), 1,
      aux_sym_call_expression_repeat1,
  [2282] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_SEMI,
    ACTIONS(336), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym__statement_list_repeat1,
  [2295] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_RPAREN,
    ACTIONS(338), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_argument_list_repeat1,
  [2308] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(76), 1,
      sym_parenthesized_expression,
  [2318] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_block,
  [2328] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 2,
      anon_sym_DOT,
      anon_sym_LPAREN,
  [2344] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym_block,
  [2354] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(78), 1,
      sym_parenthesized_expression,
  [2364] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(6), 1,
      sym_block,
  [2374] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_SEMI,
  [2381] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_identifier,
  [2388] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      ts_builtin_sym_end,
  [2395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 41,
  [SMALL_STATE(8)] = 79,
  [SMALL_STATE(9)] = 113,
  [SMALL_STATE(10)] = 151,
  [SMALL_STATE(11)] = 203,
  [SMALL_STATE(12)] = 255,
  [SMALL_STATE(13)] = 289,
  [SMALL_STATE(14)] = 341,
  [SMALL_STATE(15)] = 390,
  [SMALL_STATE(16)] = 439,
  [SMALL_STATE(17)] = 472,
  [SMALL_STATE(18)] = 521,
  [SMALL_STATE(19)] = 570,
  [SMALL_STATE(20)] = 619,
  [SMALL_STATE(21)] = 668,
  [SMALL_STATE(22)] = 717,
  [SMALL_STATE(23)] = 766,
  [SMALL_STATE(24)] = 815,
  [SMALL_STATE(25)] = 864,
  [SMALL_STATE(26)] = 913,
  [SMALL_STATE(27)] = 962,
  [SMALL_STATE(28)] = 1011,
  [SMALL_STATE(29)] = 1043,
  [SMALL_STATE(30)] = 1075,
  [SMALL_STATE(31)] = 1107,
  [SMALL_STATE(32)] = 1139,
  [SMALL_STATE(33)] = 1180,
  [SMALL_STATE(34)] = 1212,
  [SMALL_STATE(35)] = 1244,
  [SMALL_STATE(36)] = 1276,
  [SMALL_STATE(37)] = 1308,
  [SMALL_STATE(38)] = 1340,
  [SMALL_STATE(39)] = 1372,
  [SMALL_STATE(40)] = 1399,
  [SMALL_STATE(41)] = 1426,
  [SMALL_STATE(42)] = 1453,
  [SMALL_STATE(43)] = 1480,
  [SMALL_STATE(44)] = 1520,
  [SMALL_STATE(45)] = 1546,
  [SMALL_STATE(46)] = 1572,
  [SMALL_STATE(47)] = 1602,
  [SMALL_STATE(48)] = 1628,
  [SMALL_STATE(49)] = 1666,
  [SMALL_STATE(50)] = 1708,
  [SMALL_STATE(51)] = 1744,
  [SMALL_STATE(52)] = 1776,
  [SMALL_STATE(53)] = 1802,
  [SMALL_STATE(54)] = 1828,
  [SMALL_STATE(55)] = 1854,
  [SMALL_STATE(56)] = 1880,
  [SMALL_STATE(57)] = 1922,
  [SMALL_STATE(58)] = 1961,
  [SMALL_STATE(59)] = 1998,
  [SMALL_STATE(60)] = 2034,
  [SMALL_STATE(61)] = 2070,
  [SMALL_STATE(62)] = 2106,
  [SMALL_STATE(63)] = 2142,
  [SMALL_STATE(64)] = 2178,
  [SMALL_STATE(65)] = 2214,
  [SMALL_STATE(66)] = 2230,
  [SMALL_STATE(67)] = 2243,
  [SMALL_STATE(68)] = 2256,
  [SMALL_STATE(69)] = 2269,
  [SMALL_STATE(70)] = 2282,
  [SMALL_STATE(71)] = 2295,
  [SMALL_STATE(72)] = 2308,
  [SMALL_STATE(73)] = 2318,
  [SMALL_STATE(74)] = 2328,
  [SMALL_STATE(75)] = 2336,
  [SMALL_STATE(76)] = 2344,
  [SMALL_STATE(77)] = 2354,
  [SMALL_STATE(78)] = 2364,
  [SMALL_STATE(79)] = 2374,
  [SMALL_STATE(80)] = 2381,
  [SMALL_STATE(81)] = 2388,
  [SMALL_STATE(82)] = 2395,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(32),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(79),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(10),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(77),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(38),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(18),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(57),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(57),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, .production_id = 4),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, .production_id = 4),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2, .production_id = 12),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2, .production_id = 12),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2, .production_id = 12), SHIFT_REPEAT(72),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, .production_id = 8),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4, .production_id = 8),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 3, .production_id = 14),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 3, .production_id = 14),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_statement, 2),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_statement, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, .production_id = 11),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, .production_id = 11),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subscript_expression_repeat1, 2, .production_id = 15),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subscript_expression_repeat1, 2, .production_id = 15),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subscript_expression_repeat1, 2, .production_id = 15), SHIFT_REPEAT(21),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subscript_expression, 4, .production_id = 9),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subscript_expression, 4, .production_id = 9),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subscript_expression, 5, .production_id = 13),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subscript_expression, 5, .production_id = 13),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_declaration, 2, .production_id = 3),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_declaration, 2, .production_id = 3),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_declaration_repeat1, 2, .production_id = 7),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_declaration_repeat1, 2, .production_id = 7),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_declaration_repeat1, 2, .production_id = 7), SHIFT_REPEAT(11),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_declaration, 1),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_declaration, 1),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subscript_expression_repeat1, 3, .production_id = 16),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subscript_expression_repeat1, 3, .production_id = 16),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_declaration_repeat1, 3, .production_id = 10),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_declaration_repeat1, 3, .production_id = 10),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_declaration_repeat1, 2),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_declaration_repeat1, 2),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 6),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 6),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, .production_id = 5),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 3, .production_id = 5),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print, 2),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print, 2),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2, .production_id = 2),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 2, .production_id = 2),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 4),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [296] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [304] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_statement, 3, .production_id = 6),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [320] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list_repeat1, 2), SHIFT_REPEAT(5),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_list_repeat1, 2),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_list, 2),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [331] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2), SHIFT_REPEAT(80),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_list, 1),
  [338] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(17),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [343] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_bml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
